# Generated by Django 6.0.4 on 2026-04-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.TextField()),
                ('password_salt', models.CharField(max_length=64)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('student', 'Student')], max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('rsa_public_key', models.TextField()),
                ('rsa_private_key', models.TextField()),
                ('encrypted_full_name', models.TextField()),
                ('encrypted_email_data', models.TextField()),
                ('encrypted_phone', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
    ]
