# Generated by Django 6.0.4 on 2026-05-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ecc_private_key',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ecc_public_key',
            field=models.TextField(default=''),
        ),
    ]
