# Generated by Django 6.0.4 on 2026-05-01 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_encrypted_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='key_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='keys_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_key_rotation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='KeyAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('decrypt', 'Data Decrypted'), ('rotate', 'Key Rotated'), ('export', 'Key Exported'), ('login', 'Key Loaded on Login')], max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_key_actions', to='core.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_access_logs', to='core.userprofile')),
            ],
            options={
                'db_table': 'key_access_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
