# Generated by Django 5.2.7 on 2026-05-02 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_class_id_alter_classenrollment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('token_signature', models.TextField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('device_label', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secure_sessions', to='core.userprofile')),
            ],
            options={
                'db_table': 'secure_sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='SessionActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('expired', 'Session Expired'), ('hijack', 'Hijack Attempt Detected'), ('invalid_token', 'Invalid Token'), ('concurrent', 'Concurrent Session Terminated')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='core.userprofile')),
            ],
            options={
                'db_table': 'session_activity_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
