# Generated by Django 6.0.4 on 2026-05-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userprofile_encrypted_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentrequest',
            name='encrypted_student_id_number',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='parentrequest',
            name='id_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/'),
        ),
    ]
