# Generated by Django 6.0.4 on 2026-05-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_parentrequest_encrypted_student_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='subject',
            field=models.CharField(choices=[('mathematics', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('english', 'English'), ('literature', 'Literature'), ('history', 'History'), ('geography', 'Geography'), ('computer_science', 'Computer Science'), ('economics', 'Economics'), ('accounting', 'Accounting'), ('business_studies', 'Business Studies'), ('art', 'Art'), ('music', 'Music'), ('physical_education', 'Physical Education'), ('islamic_studies', 'Islamic Studies'), ('bangla', 'Bangla'), ('philosophy', 'Philosophy'), ('psychology', 'Psychology'), ('statistics', 'Statistics')], default='english', max_length=50),
        ),
    ]
